name: "Issue Greeter"
on: [issues]

jobs:
  issue-greeter:
    runs-on: ubuntu-latest
    steps:
      - name: "Greeter"
        uses: anishanne/greeter@V1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: "Hey @{user}! Welcome to the **Algo-Phantoms-Frontend** repo. We're very happy to have you on board. Thanks for creating an issue which may eventually lead to the project's enhancement. Maintainers might be on their way to help you provide follow-up on the issue."


